export const UPDATE_ACTIVE_PROJECT = 'UPDATE_ACTIVE_PROJECT';
export const UPDATE_PROJECTS_ARRAY = 'UPDATE_PROJECTS_ARRAY';
export const ADD_TODO_TASK_FOR_ACTIVE_PROJECT = 'ADD_TODO_TASK_FOR_ACTIVE_PROJECT';
export const DRAG_TASK_IN_SAME_COLUMN = 'DRAG_TASK_IN_SAME_COLUMN';
export const DRAG_TASK_IN_OTHER_COLUMN = 'DRAG_TASK_IN_OTHER_COLUMN';
export const SET_EXIST_PROJECTS = 'SET_EXIST_PROJECTS';
export const UPDATE_CONFIRMED_PROJECT = 'UPDATE_CONFIRMED_PROJECT';
export const UPDATE_NOTIF_COUNTER = 'UPDATE_NOTIF_COUNTER';
