export const ADD_TODO_TASK_FOR_ACTIVE_PROJECT = 'ADD_TODO_TASK_FOR_ACTIVE_PROJECT';
export const DRAG_TASK_IN_SAME_COLUMN = 'DRAG_TASK_IN_SAME_COLUMN';
export const DRAG_TASK_IN_OTHER_COLUMN = 'DRAG_TASK_IN_OTHER_COLUMN';

export const START_INITIALIZE_PROJECTS = 'START_INITIALIZE_PROJECTS';
export const SUCCESS_INITIALIZE_PROJECTS = 'SUCCESS_INITIALIZE_PROJECTS';
export const FAIL_INITIALIZE_PROJECTS = 'FAIL_INITIALIZE_PROJECTS';

export const START_ADD_NEW_PROJECT = 'START_ADD_NEW_PROJECT';
export const SUCCESS_ADD_NEW_PROJECT = 'SUCCESS_ADD_NEW_PROJECT';
export const FAIL_ADD_NEW_PROJECT = 'FAIL_ADD_NEW_PROJECT';

export const CHANGE_ACTIVE_PROJECT = 'CHANGE_ACTIVE_PROJECT';

export const START_DELETE_PROJECT = 'START_DELETE_PROJECT';
export const SUCCESS_DELETE_PROJECT = 'SUCCESS_DELETE_PROJECT';
export const FAIL_DELETE_PROJECT = 'FAIL_DELETE_PROJECT';

export const START_EDIT_PROJECT_NAME = 'START_EDIT_PROJECT_NAME';
export const SUCCESS_EDIT_PROJECT_NAME = 'SUCCESS_EDIT_PROJECT_NAME';
export const FAIL_EDIT_PROJECT_NAME = 'FAIL_EDIT_PROJECT_NAME';

export const CLOSE_SETTING_PROJECT_MODAL = 'CLOSE_SETTING_PROJECT_MODAL';
export const SHOW_SETTING_PROJECT_MODAL = 'SHOW_SETTING_PROJECT_MODAL';

export const START_INITIALIZE_ACTIVEPROJECT_MEMBERS = 'START_INITIALIZE_ACTIVEPROJECT_MEMBERS';
export const SUCCESS_INITIALIZE_ACTIVEPROJECT_MEMBERS = 'SUCCESS_INITIALIZE_ACTIVEPROJECT_MEMBERS';
export const FAIL_INITIALIZE_ACTIVEPROJECT_MEMBERS = 'FAIL_INITIALIZE_ACTIVEPROJECT_MEMBERS';

export const START_USER_LEAVE_PROJECT = 'START_USER_LEAVE_PROJECT';
// FOR SUCCESS USER LEAVE, WE USE SUCCESS_DELETE_PROJECT ACTION
export const FAIL_USER_LEAVE_PROJECT = 'FAIL_USER_LEAVE_PROJECT';

export const START_INVITE_MEMBER = 'START_INVITE_MEMBER';
export const SUCCESS_INVITE_MEMBER = 'SUCCESS_INVITE_MEMBER';
export const FAIL_INVITE_MEMBER = 'FAIL_INVITE_MEMBER';

export const START_DELETE_MEMBER = 'START_DELETE_MEMBER';
export const SUCCESS_DELETE_MEMBER = 'SUCCESS_DELETE_MEMBER';
export const FAIL_DELETE_MEMBER = 'FAIL_DELETE_MEMBER';

export const OPEN_NOTIFICATION_STATUS = 'OPEN_NOTIFICATION_STATUS';
export const CLOSE_NOTIFICATION_STATUS = 'CLOSE_NOTIFICATION_STATUS';

export const START_CONFIRMED_INVITE = 'START_CONFIRMED_INVITE';
export const SUCCESS_CONFIRMED_INVITE = 'SUCCESS_CONFIRMED_INVITE';
export const FAIL_CONFIRMED_INVITE = 'FAIL_CONFIRMED_INVITE';

export const START_INCONFIRMED_INVITE = 'START_INCONFIRMED_INVITE';
export const SUCCESS_INCONFIRMED_INVITE = 'SUCCESS_INCONFIRMED_INVITE';
export const FAIL_INCONFIRMED_INVITE = 'FAIL_INCONFIRMED_INVITE';

export const UPDATE_INCONFIRMED_PROJECT = 'UPDATE_INCONFIRMED_PROJECT';
export const UPDATE_NOTIF_COUNTER = 'UPDATE_NOTIF_COUNTER';

export const SUCCESS_GET_USER_PROFILE_DATA = 'GET_USER_PROFILE_DATA';
export const FAIL_GET_USER_PROFILE_DATA = 'FAIL_GET_USER_PROFILE_DATA';
